Extend pkg_tar rule with stamp_mtime attribute
bazelbuild/rules_pkg pull request #285
Opened 2021-01-29 18:28 UTC by dennis3620

This change extends the `pkg_tar` rule for stamp support for files' mtime. The attribute `stamp_mtime` contains a "volatile" workspace status command key which allows to set dynamic mtime for files inside tar archives. The value of the key depends on the workspace status command result but only "volatile" keys are provided as input to `pkg_tar` rule.

The motivation behind this change relates to #149 and #192. Files are build with Bazel and added as tar archive to `container_image` rule ([rules_docker](https://github.com/bazelbuild/rules_docker#container_image-1)). These files are served by nginx inside the container. This change should provide proper ETag values for nginx which relies on file's last modification date for caching.

2021-01-30 03:50 UTC, aiuto requested changes

2021-01-30 03:50 UTC, aiuto commented on pkg/docs/reference.md
> +          stamp_mtime = "{STAMP_MTIME}",
Why is this using a differen name than BUILD_TIMESTAMP?

2021-01-30 04:06 UTC, aiuto commented
Let's discuss solutions in an issue first.  I would like to to have as many people as possible weigh in on what is useful.
There are a lot of questions
- do we change the stamp of every file?
- does that include files which came from pre-made archives that have a particular timestamp of their own?
- some people want to put the timestamp into the output filename. While I find that dubious, any stamping solution should consider it.
- Why is stamp_mtime an attribute?  Why not just support the --stamp flag. That seems to be the API of least surprise.
- and.... no solutions that just to .tar.   We need do do the appropriate thing for each of pkg_zip, pkg_deb and pkg_rpm.  But that makes getting the API right before doing any code even more important.

2021-02-03 18:04 UTC, nacl commented
Design and requirements gathering is tracked in #287.

2021-02-04 03:50 UTC, aiuto reviewed
I tried my own variant in #288.
It uses a similar technique, but supports --stamp directly, without having to modify the pkg_tar rule.
I prefer that because it feeds into the `stamp` behavior of the built-in rules like cc_binary. https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary

Let's finish discussion of what we want in #287 and then see what to implement.

2021-02-04 03:50 UTC, aiuto commented on pkg/pkg.bzl
> +            fail("You set stamp_mtime, but this doesn't contain a valid key variable")
This should just use BUILD_STAMP.  We don't need the flexibility to let the user set an arbitrary variable out of the volatile status file. This adds complexity that no one asked for.

2021-02-04 03:50 UTC, aiuto commented on pkg/tests/workspace_status.sh
> +STAMP_MTIME ${stamp_mtime}
Should be BUILD_TIMESTAMP

2021-05-03 22:00 UTC, aiuto commented
I'm opting for the path I have taken in #288.  That will works the same way as the `stamp` attribute in the *_binary rules.

2021-05-03 22:00 UTC, closed without merging