add recurse option to pkg_zip to maintain directory structure
bazelbuild/rules_pkg pull request #428
Opened 2021-10-04 21:59 UTC by hborawski

Need to maintain the zip directory structure for zipping cocoapods as a part of the build, otherwise the glob wont match from the podspec file (or i'd end up matching test files from a test_spec as well as source files)

```ruby
...
s.source_files = "SomePod/Sources/**/*.swift"
s.test_spec do |tests|
  tests.source_files = "SomePod/Tests/**/*.swift"
end
```

`pkg_zip` with `glob(["SomePod/Sources/**/*.swift"])` will produce a zip with all swift files in a flat directory

I can solve this simple example with `package_dir = 'SomePod/Sources'` but looking for a longer term solution because i want to use this on pods with multiple subspecs

2021-10-05 00:08 UTC, aiuto commented
Can you create an issue that describes the broader problem?
My inclination is to not even review this. The main reason is that it is a special hack to pkg_zip, and not reusable across all the other package types.  This should be implemented as extensions to pkg_files, if anywhere.

2021-10-05 00:11 UTC, aiuto requested changes
Needs discussion first.

2021-10-12 17:31 UTC, hborawski commented
issue created: https://github.com/bazelbuild/rules_pkg/issues/434

2021-11-10 21:48 UTC, hborawski commented
Closing due to resolution in #434

2021-11-10 21:48 UTC, closed without merging