compute_data_path should add the workspace_root
bazelbuild/rules_pkg pull request #478
Opened 2021-11-25 13:53 UTC by BoleynSu

pkg_tar rule will produce a tarbal with files
named exteranl/workspace_name/path_to_file
even if `strip_prefix = "."` currently. This commit
fixes it.

2021-11-25 14:05 UTC, BoleynSu commented
@aiuto @nacl PTAL

2021-11-25 18:32 UTC, aiuto requested changes
Please describe the problem behavior in an issue first, with before and after examples.
From what it looks like, 
Als, any behavior changing PR must include tests.

2021-11-28 12:39 UTC, BoleynSu commented
@aiuto I will open an issue and add more tests for the PR later. Will ping you then.

2021-12-03 14:49 UTC, BoleynSu commented
Fixes #479 
Hi @aiuto, I have added the issue and the test. PTAL

2021-12-03 16:32 UTC, nacl commented
Thanks for the PR!

Without looking at this review in any particular detail, do you get the desired results (removal of the workspace root) if you pass a `pkg_files` target like this to `pkg_tar` (see `pkg/mappings.bzl`):

```starlark
# Needed new loads
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")

pkg_files(
    name = "your-files",
    srcs = ["your", "files", "here"],
    strip_prefix = strip_prefix.from_pkg(""),
)
```

This is the direction we're leaning towards in the long-term: `pkg_files` is intended to be a package-type-independent means for mapping bazel targets into packaging outputs, and is intended to replace all path remapping functionality in packaging rules (like `strip_prefix` in `pkg_tar`).

That being said, I'm not sure about the long-term fate of `pkg/path.bzl` -- most of the functionality needed for `pkg_files` is already included in `pkg/mappings.bzl`.  @aiuto may have a more concrete opinion on this than I.

2021-12-04 04:07 UTC, BoleynSu commented
> Thanks for the PR!
> 
> Without looking at this review in any particular detail, do you get the desired results (removal of the workspace root) if you pass a `pkg_files` target like this to `pkg_tar` (see `pkg/mappings.bzl`):
> 
> ```python
> # Needed new loads
> load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
> 
> pkg_files(
>     name = "your-files",
>     srcs = ["your", "files", "here"],
>     strip_prefix = strip_prefix.from_pkg(""),
> )
> ```
> 
> This is the direction we're leaning towards in the long-term: `pkg_files` is intended to be a package-type-independent means for mapping bazel targets into packaging outputs, and is intended to replace all path remapping functionality in packaging rules (like `strip_prefix` in `pkg_tar`).
> 
> That being said, I'm not sure about the long-term fate of `pkg/path.bzl` -- most of the functionality needed for `pkg_files` is already included in `pkg/mappings.bzl`. @aiuto may have a more concrete opinion on this than I.

I verified that pkg_files also has the same issue, i.e. the following won't pass the test.

```python
pkg_files(
    name = "your-files",
    srcs = ["BUILD"],
    strip_prefix = strip_prefix.from_pkg(""),
)
pkg_tar(
    name = "test-tar-strip_prefix-external_workspace",
    srcs = [
         "your-files",
         #"BUILD",
    ],
    strip_prefix = ".",
    visibility = ["//visibility:public"],
)
```

2021-12-04 16:04 UTC, nacl commented
I see.  I checked out your change locally.  When using `pkg_files` like I described above, I found that your new test passed.  Code is available in [topic/i479-compute_data_path](https://github.com/nacl/rules_pkg/tree/topic/i479-compute_data_path) in my personal fork.

Please take a look; I could be missing something.

2021-12-04 16:12 UTC, BoleynSu commented
Hi @nacl, do you mean the pkg_tat failed but pkg_files passed? Would you
mind also pushing yout changes in tests/BUILD to your repo?

Sent from https://boleyn.su/phone

On Sun, Dec 5, 2021, 00:04 Andrew Psaltis ***@***.***> wrote:

> I see. I checked out your change locally. When using pkg_files like I
> described above, I found that your new test passed. Code is available in
> topic/i479-compute_data_path
> <https://github.com/nacl/rules_pkg/tree/topic/i479-compute_data_path> in
> my personal fork.
>
> Please take a look; I could be missing something.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-986050651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXVSKEBBW7KA2HQ5VB2IFLUPI3Y7ANCNFSM5IYTA5GA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-04 16:17 UTC, BoleynSu commented
Hi @nacl, I just saw your commit. The only difference is that in my local
test I kept the strip_prefix attr in pkg_tar. Would you mind try that?

Sent from https://boleyn.su/phone

On Sun, Dec 5, 2021, 00:12 Boleyn Su ***@***.***> wrote:

> Hi @nacl, do you mean the pkg_tat failed but pkg_files passed? Would you
> mind also pushing yout changes in tests/BUILD to your repo?
>
> Sent from https://boleyn.su/phone
>
> On Sun, Dec 5, 2021, 00:04 Andrew Psaltis ***@***.***>
> wrote:
>
>> I see. I checked out your change locally. When using pkg_files like I
>> described above, I found that your new test passed. Code is available in
>> topic/i479-compute_data_path
>> <https://github.com/nacl/rules_pkg/tree/topic/i479-compute_data_path> in
>> my personal fork.
>>
>> Please take a look; I could be missing something.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-986050651>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAXVSKEBBW7KA2HQ5VB2IFLUPI3Y7ANCNFSM5IYTA5GA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-12-04 21:02 UTC, nacl commented
I readded `strip_prefix` to `pkg_tar` as you had it above, and your test still passed

`strip_prefix` on `pkg_tar` should only interact with file inputs.  It should have no interaction with inputs from `pkg_files` and similar rules.

2021-12-05 02:58 UTC, BoleynSu commented
> I readded `strip_prefix` to `pkg_tar` as you had it above, and your test still passed in my environment.
>
> What's supposed to happen is that `pkg_tar`'s `strip_prefix` attribute should only interact with file inputs. It should not interact with `pkg_files` and similar rules.


I have uploaded my working example at https://github.com/BoleynSu/rules_pkg/tree/demo. FYI, I am using Bazel 4.2.1.

```text
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
```

Please take a look.

2021-12-05 03:59 UTC, BoleynSu commented
I just realize I am doing it wrongly. I should also use an external pkg_tar when I am using an external pkg_files. Otherwise, the provider won't match.

So, the conclusion is that pkg_files works as expected.

@nacl should I close the issue as WONT FIX or we still wants to fix pkg_tar?

2021-12-06 16:43 UTC, nacl commented
> I just realized I was doing it wrongly. I should also use an external pkg_tar when I am using an external pkg_files. Otherwise, the provider won't match.

Huh.  That's odd.  It's weird that this is the case -- IIRC providers are just structures in the global namespace. and where they are declared shouldn't really matter, but I could easily be mistaken.  @aiuto, do you know what might be happening here?

Regardless, I don't think this is a problem in rules_pkg (if it is a problem at all).  Thank you for double-checking.

> So, the conclusion is that pkg_files works as expected.

Great to hear.  I'll close this out.

For additional context, I'd be far more willing to accept this if it weren't a breaking change.  Even though this behavior is bad, changing this would impact anything that uses `path.bzl` to create paths, including rules like `pkg_zip`, and would require users to migrate.  It's not a big deal, but we'd rather people just migrate directly to using `pkg_files` and friends.

If you need something like this in tar files and the `pkg_filegroup` framework (`pkg_files`, etc.), I think `remap_paths` will do the right thing.

FWIW, this functionality for `pkg_files` has [tests](https://github.com/bazelbuild/rules_pkg/blob/3c520a1becd011aa3c578a5edef27c180936adea/tests/mappings/mappings_external_repo_test.bzl).  I'd be happy to accept additions to the test framework if you have any ideas.

2021-12-06 16:43 UTC, closed without merging

2021-12-07 00:32 UTC, BoleynSu commented
For the provider issue, it is kinda like

a.py:

import b
assert(x!=b.x)

b.py: symbolic link of a.py

Would you mind documenting the deprecation of strip_prefix functionality of
pkg_tar/pkg_whatever? So that other people could avoid my situation in the
first place.

Sent from https://boleyn.su/phone

On Tue, Dec 7, 2021, 00:43 Andrew Psaltis ***@***.***> wrote:

> I just realized I was doing it wrongly. I should also use an external
> pkg_tar when I am using an external pkg_files. Otherwise, the provider
> won't match.
>
> Huh. That's odd. It's weird that this is the case -- IIRC providers are
> just structures in the global namespace. and where they are declared
> shouldn't really matter, but I could easily be mistaken. @aiuto
> <https://github.com/aiuto>, do you know what might be happening here?
>
> Regardless, I don't think this is a problem in rules_pkg (if it is a
> problem at all). Thank you for double-checking.
>
> So, the conclusion is that pkg_files works as expected.
>
> Great to hear. I'll close this out.
>
> For additional context, I'd be far more willing to accept this if it
> weren't a breaking change. Even though this behavior is bad, changing this
> would impact anything that uses path.bzl to create paths, including rules
> like pkg_zip, and would require users to migrate. It's not a big deal,
> but we'd rather people just migrate directly to using pkg_files and
> friends.
>
> If you need something like this in tar files and the pkg_filegroup
> framework (pkg_files, etc.), I think remap_paths will do the right thing.
>
> FWIW, this functionality for pkg_files has tests
> <https://github.com/bazelbuild/rules_pkg/blob/3c520a1becd011aa3c578a5edef27c180936adea/tests/mappings/mappings_external_repo_test.bzl>.
> I'd be happy to accept additions to the test framework if you have any
> ideas.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-986952604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXVSKFVMLOY7V5UF63T4KLUPTR4XANCNFSM5IYTA5GA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-10 06:23 UTC, aiuto commented
The location of the bzl file declaring a provider matters. The package
becomes the namespace for it to prevent symbol clashes.

On Mon, Dec 6, 2021 at 7:32 PM Boleyn Su ***@***.***> wrote:

> For the provider issue, it is kinda like
>
> a.py:
>
> import b
> assert(x!=b.x)
>
> b.py: symbolic link of a.py
>
> Would you mind documenting the deprecation of strip_prefix functionality of
> pkg_tar/pkg_whatever? So that other people could avoid my situation in the
> first place.
>
> Sent from https://boleyn.su/phone
>
> On Tue, Dec 7, 2021, 00:43 Andrew Psaltis ***@***.***> wrote:
>
> > I just realized I was doing it wrongly. I should also use an external
> > pkg_tar when I am using an external pkg_files. Otherwise, the provider
> > won't match.
> >
> > Huh. That's odd. It's weird that this is the case -- IIRC providers are
> > just structures in the global namespace. and where they are declared
> > shouldn't really matter, but I could easily be mistaken. @aiuto
> > <https://github.com/aiuto>, do you know what might be happening here?
> >
> > Regardless, I don't think this is a problem in rules_pkg (if it is a
> > problem at all). Thank you for double-checking.
> >
> > So, the conclusion is that pkg_files works as expected.
> >
> > Great to hear. I'll close this out.
> >
> > For additional context, I'd be far more willing to accept this if it
> > weren't a breaking change. Even though this behavior is bad, changing
> this
> > would impact anything that uses path.bzl to create paths, including rules
> > like pkg_zip, and would require users to migrate. It's not a big deal,
> > but we'd rather people just migrate directly to using pkg_files and
> > friends.
> >
> > If you need something like this in tar files and the pkg_filegroup
> > framework (pkg_files, etc.), I think remap_paths will do the right thing.
> >
> > FWIW, this functionality for pkg_files has tests
> > <
> https://github.com/bazelbuild/rules_pkg/blob/3c520a1becd011aa3c578a5edef27c180936adea/tests/mappings/mappings_external_repo_test.bzl
> >.
> > I'd be happy to accept additions to the test framework if you have any
> > ideas.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-986952604
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAXVSKFVMLOY7V5UF63T4KLUPTR4XANCNFSM5IYTA5GA
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-987428679>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXHHHG3HGP5BBBLQN4XD4TUPVIZRANCNFSM5IYTA5GA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-10 09:39 UTC, BoleynSu commented
Just in case you missed it, @aiuto, the issue still exists for pkg_tar but
not pkg_files. However, the fix results in a breaking change ( since the
old behavior is buggy). Do you think we should fix it? It should only
affect those who used it in a buggy way.

Sent from https://boleyn.su/phone

On Fri, Dec 10, 2021, 14:23 aiuto ***@***.***> wrote:

> The location of the bzl file declaring a provider matters. The package
> becomes the namespace for it to prevent symbol clashes.
>
> On Mon, Dec 6, 2021 at 7:32 PM Boleyn Su ***@***.***> wrote:
>
> > For the provider issue, it is kinda like
> >
> > a.py:
> >
> > import b
> > assert(x!=b.x)
> >
> > b.py: symbolic link of a.py
> >
> > Would you mind documenting the deprecation of strip_prefix functionality
> of
> > pkg_tar/pkg_whatever? So that other people could avoid my situation in
> the
> > first place.
> >
> > Sent from https://boleyn.su/phone
> >
> > On Tue, Dec 7, 2021, 00:43 Andrew Psaltis ***@***.***> wrote:
> >
> > > I just realized I was doing it wrongly. I should also use an external
> > > pkg_tar when I am using an external pkg_files. Otherwise, the provider
> > > won't match.
> > >
> > > Huh. That's odd. It's weird that this is the case -- IIRC providers are
> > > just structures in the global namespace. and where they are declared
> > > shouldn't really matter, but I could easily be mistaken. @aiuto
> > > <https://github.com/aiuto>, do you know what might be happening here?
> > >
> > > Regardless, I don't think this is a problem in rules_pkg (if it is a
> > > problem at all). Thank you for double-checking.
> > >
> > > So, the conclusion is that pkg_files works as expected.
> > >
> > > Great to hear. I'll close this out.
> > >
> > > For additional context, I'd be far more willing to accept this if it
> > > weren't a breaking change. Even though this behavior is bad, changing
> > this
> > > would impact anything that uses path.bzl to create paths, including
> rules
> > > like pkg_zip, and would require users to migrate. It's not a big deal,
> > > but we'd rather people just migrate directly to using pkg_files and
> > > friends.
> > >
> > > If you need something like this in tar files and the pkg_filegroup
> > > framework (pkg_files, etc.), I think remap_paths will do the right
> thing.
> > >
> > > FWIW, this functionality for pkg_files has tests
> > > <
> >
> https://github.com/bazelbuild/rules_pkg/blob/3c520a1becd011aa3c578a5edef27c180936adea/tests/mappings/mappings_external_repo_test.bzl
> > >.
> > > I'd be happy to accept additions to the test framework if you have any
> > > ideas.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-986952604
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AAXVSKFVMLOY7V5UF63T4KLUPTR4XANCNFSM5IYTA5GA
> > >
> > > .
> > > Triage notifications on the go with GitHub Mobile for iOS
> > > <
> >
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> > >
> > > or Android
> > > <
> >
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> > >.
> > >
> > >
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-987428679
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAXHHHG3HGP5BBBLQN4XD4TUPVIZRANCNFSM5IYTA5GA
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_pkg/pull/478#issuecomment-990651830>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXVSKFNFIFXNMLWHNNFEH3UQGMFRANCNFSM5IYTA5GA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>